### ISSUE TITLE
Ingest Error when Input Cols !== DS Fields

### ISSUE THREAD

**Issue by vforgione** [UrbanCCD-UChicago/plenario2#138]
if a table has fewer fields than the input data, it will fail. this may or may not be a bad thing. i tried setting up a table with only a few columns that i wanted from a data set rather than adding all of them.

```
** (Postgrex.Error) ERROR 42601 (syntax_error): INSERT has more expressions than target columns
    (ecto) lib/ecto/adapters/sql.ex:200: Ecto.Adapters.SQL.query!/5
    (plenario2) lib/plenario2_etl/worker.ex:220: Plenario2Etl.Worker.template_query!/3
    (plenario2) lib/plenario2_etl/worker.ex:95: Plenario2Etl.Worker.load_chunk!/4
```

**Comment by HeyZoos** [comment]
Hmm, what behavior would we like here? The rows are converted to keyword lists before being rendered to an INSERT, it'd be pretty simple to only use the keys provided by a meta.

**Comment by vforgione** [comment]
i think using the keys provided by the meta would be _safer_; i don't know which is better. i guess whatever was originally defined and approved is only what we should use..?
