### ISSUE TITLE
Constraints can still be deleted outside of `new` meta state

### ISSUE THREAD

**Issue by HeyZoos** [UrbanCCD-UChicago/plenario2#166]
To replicate
- add a unique constraint
- put meta into state `awaiting_first_import`,
- delete the constraint
- attempt to add again (will say the data set is locked)

**Comment by vforgione** [comment]
Bunk, I say, bunk!

![screenshot from 2018-02-15 16-49-20](https://user-images.githubusercontent.com/4360430/36285211-43b2232a-1270-11e8-858b-e58d7390d347.png)
