### ISSUE TITLE
Missing Date Picker (Safari 11)

### ISSUE THREAD

**Issue by seanshahkarami** [UrbanCCD-UChicago/plenario2#205]
Missing date picker on: https://dev.plenar.io/explore

<img width="1280" alt="plenario no date picker" src="https://user-images.githubusercontent.com/6498106/36801605-30930644-1c78-11e8-8840-ccf414cb3cc8.png">

**Comment by vforgione** [comment]
@seanshahkarami i pushed an update last night. can you check this out and see if it's still screwy?

**Comment by vforgione** [comment]
Seems to be working now, along with having better date time parsing of plain text. 

<img width="1188" alt="screen shot 2018-03-08 at 10 56 09 am" src="https://user-images.githubusercontent.com/4360430/37164291-7691118e-22bf-11e8-912b-3ee46838ab47.png">
