### ISSUE TITLE
Datetime representations cause unecessary diff creation

### ISSUE THREAD

**Issue by HeyZoos** [UrbanCCD-UChicago/plenario2#209]
```
[info] Creating DataSetDiff: %{changed_on: #DateTime<2018-03-02 18:31:56.858543Z>, column: "Date", constraint_values: %{"Incident Report Number": "20161860602"}, etl_job_id: 24, meta_id: 5, original: "~N[2016-07-03 00:00:00]", unique_constraint_id: 5, update: "\"07/03/2016\""}
```

Re ingesting the same dataset creates a diff for values `"\"07/03/2016\""` & `"~N[2016-07-03 00:00:00]"`

**Comment by vforgione** [comment]
Since we took diffs out of commission I'm going to close this for now. If and when we add diffing back into the mix then we can revisit this problem.
