### ISSUE TITLE
Data Set Metadata

### ISSUE THREAD

**Issue by vforgione** [UrbanCCD-UChicago/plenario2#234]
A feature request was brought up the weekly call this morning regarding storing metadata about data sets. The gist of the idea was the data set owners could be able to store JSON blobs to help drive application usage of API results.

I'd like to get a discussion going regarding what specific use cases people have in mind, is there room for Plenario to use this data too, how this should be stored and retrieved.

**Comment by tomschenkjr** [comment]
Largely, let me point to Chicago/opengrid#313 as the source for this discussion. Mostly, graphing capability available in OpenGrid is disabled at opengrid.io (but we use it internally and is in the code). This related back to what @nfspeedypur discussed because of "missing metadata".

**Comment by vforgione** [comment]
Going to be handled with #264
