### ISSUE TITLE
Resolve JS security vulnerability in dependency

### ISSUE THREAD

**Issue by brlodi** [UrbanCCD-UChicago/plenario2#307]
The current version of **node-sass** depends on **request** 2.79.0, which in turn depends on a package with a known security vulnerability. More recent versions of **request** have resolved this, but have not yet been upgraded in **node-sass**.

This is tracked in sass/node-sass#2355 and will be resolved in the next server update of **node-sass**. We should upgrade our **node-sass** dependency in `package.json` at that time.

**Comment by vforgione** [comment]
Just want to revisit this. Did these imbeciles ever get their shit together?

**Comment by brlodi** [comment]
For completeness, sass/node-sass#2312 and subsequent release is what we, and most of the rest of the JavaScript ecosystem, are waiting on.
