### ISSUE TITLE
`/explore` not getting any search results

### ISSUE THREAD

**Issue by HeyZoos** [UrbanCCD-UChicago/plenario2#313]
![image](https://user-images.githubusercontent.com/9408481/40083227-802ceed4-5861-11e8-9409-5b7a1e89d63b.png)

**Comment by vforgione** [comment]
I could be wrong, but I don't think there are any _live_ data sets around Chicago at the moment. There are a bunch of Seattle ones though: https://dev.plenar.io/explore?_utf8=%E2%9C%93&starting_on=2015-05-01&ending_on=2018-05-31&coords=%5B%5B39.63953756436671%2C-127.05188010435573%5D%2C%5B49.32512199104003%2C-127.05188010435573%5D%2C%5B49.32512199104003%2C-106.12125680580766%5D%2C%5B39.63953756436671%2C-106.12125680580766%5D%5D&zoom=4

**Comment by vforgione** [comment]
No. After my big AoT migration, they are fundamentally distinct under the hood and will not be captured with the rest of the metas.

**Comment by HeyZoos** [comment]
:+1:
