### ISSUE TITLE
API 4xx Errors

### ISSUE THREAD

**Issue by vforgione** [UrbanCCD-UChicago/plenario2#333]
We need to ensure that we are capturing and responding to the following:

- [x] 404 when a detail endpoint is called without a matching data set
- [x] 400 when any params cannot be processed
- [x] 422 when params are processed but ultimately get bonked by the database

These absolutely do not need helpful messages, suggestions or any other hand holding. Just get these in the pipeline and get on with your life.

**Comment by sanilio** [comment]
Adding tests
