### ISSUE TITLE
Figure out how to wire up Data Set Creation for Massive Data Sets

### ISSUE THREAD

**Issue by vforgione** [UrbanCCD-UChicago/plenario2#340]
Related to #235 

For things like Crime Data and Divvy Rides, where the data set takes _minutes_ to just even respond to requests, we need some sort of mechanism to handle this.

One possible solution: add an extra field to the meta that says _this is a really big data set_. When that flag is true, we can either increase the timeout value for the request or turn it into some sort of background job (and still bump out the request timeout). I'm not so sure about the background job, as it would have a significantly different workflow for the users.

@HeyZoos, @brlodi, @sanilio please comment.

**Comment by brlodi** [comment]
> add an extra field to the meta that says *this is a really big data set*.

I'd argue it's less that it's a really big dataset (though I'm sure that's the underlying cause) and more of a poorly-configured, or at least insufficiently configured, source server. Ideally we'd just say that if your server can't be bothered to return at least a `202 Request Accepted` within 30 seconds or so then that's your problem.

To pick on the Divvy Trips and the City a little bit here for the sake of example:

```
> GET /api/views/fg6s-gzvg/rows.csv HTTP/1.1
> Host: data.cityofchicago.org
> User-Agent: insomnia/5.16.6
> Accept: */*

< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 28 Jun 2018 17:49:33 GMT
< Content-Type: text/csv; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Socrata-RequestId: a8tww493syofhmkgmsbh7u0yb
< Access-Control-Allow-Origin: *
< Content-disposition: attachment; filename=Divvy_Trips.csv
< Cache-Control: public, must-revalidate, max-age=21600
< ETag: W/"YWxwaGEuMTE4NDM4XzI5XzIyMTU1THVYRTFfc3E5eUd6X0xFdmRLOTZhdFBTTEEVhO3X06sMVfUWaJqVNGN6bsfILw-gzip--gzip"
< X-SODA2-Data-Out-Of-Date: false
< X-SODA2-Truth-Last-Modified: Tue, 27 Mar 2018 21:37:31 GMT
< X-SODA2-Secondary-Last-Modified: Tue, 27 Mar 2018 21:37:31 GMT
< Last-Modified: Tue, 27 Mar 2018 21:37:31 GMT
< Vary: Accept-Encoding
< Age: 64
< X-Socrata-Region: aws-us-east-1-fedramp-prod

* Received 15.3 KB chunk
* Received 16 KB chunk
* Received 16 KB chunk
...
```

It's smart enough to use a chunked (streaming) transfer, but still produces the entire content on the server side before sending the header. It should send a `200 OK` response header as soon as it starts compiling the data to transfer. Whether or not it has the first chunk immediately ready is irrelevant.

---

Unfortunately I think the best we can do (and I have no idea how to implement it) is check if the SSL handshake happens successfully, so we know we've at least connected to the target server, and then wait some arbitrarily long amount of time for it to get around to providing a header response. We have the slight benefit that such servers should be relatively quick about *bad* requests so we can somewhat safely assume that a present but silent server is formulating some huge response body.

**Comment by vforgione** [comment]
To be clear, we can verify the resource exists relatively quickly sending options and head requests, which we already do.

**Comment by HeyZoos** [comment]
Could you clarify where the workflow would be different? Data set ingest, small and large, is always carried out in the background from what I understand. Our issues with those have been due to `GenServer` timeouts and memory management.

**Comment by vforgione** [comment]
The field guesser, specifically. I think I just need to tinker around with that.

**Comment by brlodi** [comment]
If we know the resource exists, then, I don't see any problem with just putting a stupidly long timeout on it. If we want to be fancy, we could set it automatically based on like 125% of the delay for the response the last time we accessed the resource

**Comment by HeyZoos** [comment]
Hmm, streaming the 1000 or so rows off the top doesn't work for those?

**Comment by vforgione** [comment]
Ok, so Divvy trips, in particular, takes **waaaaaaaaay** too long to render server side before it even starts to send a response. I'm going to work with the people at the city to work around a solution.

This may be the lead up to building out an ingest process for _Top-N_ data sets, where the body is too large to process in a realistic time frame.

**Comment by vforgione** [comment]
Blocked until we address #377
