### ISSUE TITLE
We *DO NOT* Accept JSON API

### ISSUE THREAD

**Issue by vforgione** [UrbanCCD-UChicago/plenario2#348]
I know we're aping some of the structure of it, but we do not accept it as a body encoding. As a matter of fact, we don't accept any payloads since all of out endpoints are only GET accessible.

The following files need to be updated:

```
plenario_web/controllers/api/plugs.ex
41:        |> put_req_header("accept", "application/vnd.api+json")
60:        |> put_req_header("accept", "application/vnd.api+json")
105:    |> put_req_header("accept", "application/vnd.api+json")
123:        |> put_req_header("accept", "application/vnd.api+json")

plenario_web/controllers/api/utils.ex
241:    |> put_req_header("accept", "application/vnd.api+json")
```

Literally nowhere should the specification for this type exist, nor should be ever set the `Accept` response header (again, because we don't accept anything other than request parameters).

**Comment by HeyZoos** [comment]
`Content-Type` is the way to go. I'll open a PR replacing all the `put_req_header` calls with `put_resp_content_type`.

**Comment by HeyZoos** [comment]
Actually that doesn't address the issue.

![image](https://user-images.githubusercontent.com/9408481/42451752-20f9b2e2-8356-11e8-82f1-70b912243830.png)

The explode library decides what to send for the `Content-Type` response header based on the `accept` header of the incoming request. 

```elixir
  def with(conn, code, message) do
    {status_code, error} = find_code_in_table(code)
    content_type = accept_type(conn)

    payload = build_body(status_code, error, message, content_type)

    do_reply(conn, status_code, payload, content_type)
end
```

```elixir
  defp do_reply(conn, code, payload, content_type) do
    conn
    |> Plug.Conn.put_resp_content_type(content_type)
    |> Plug.Conn.send_resp(code, Poison.encode!(payload))
    |> Plug.Conn.halt
end
```

I think that as long as we understand why we are overriding the request header then it's alright. I can open a PR with docs explaining it. The primary benefit that the library brings to the table, for me, is that it has a big map that associates all the appropriate error responses with their status codes.

**Comment by HeyZoos** [comment]
Just to clarify the issue a bit more now, we were sending back json with the `Content-Type` header of xml. This was because browsers usually ask for xml by default, and anytime a connection is halted with the explode library it responds with a `Content-Type` header that matched the `accept` header of the request.

**Comment by HeyZoos** [comment]
That being said, it's an issue of preference imo. This code doesn't cause any errors, and doesn't affect what the server accepts in any way. This stuff only affects the client.

**Comment by vforgione** [comment]
Good call. I wasn't feeling so hot and I confused what the header was doing -- don't code while sick I guess.

At any rate, I still think we shouldn't be sending any header information about responses being something that they aren't. We also shouldn't be dictating what the client accepts. The entire API should be plain old `application/json`.

**Comment by brlodi** [comment]
I believe the issue is that the explode library doesn't handle this well, or at least we're missing the appropriate toggle to do so. As it is, without these lines explode is being handed JSON, being told it's JSON, and saying "but the client said it accepts XML, and doesn't explicitly say it accepts JSON, so I'm going to pretend this is XML and send it as such". In other words, _we're_ not sending any header information ourselves, explode is, based exclusively on the client's Accept header and not the actual response content.

**Comment by brlodi** [comment]
For example, Safari sends this Accept header: `text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`, so explode refuses to respond with JSON. What this code does is override the accept header before passing it to explode to handle, so explode doesn't itself override the response encoding.

**Comment by vforgione** [comment]
https://github.com/pkinney/explode/blob/master/lib/explode.ex#L2

This is the only valuable piece of this library. We can copy the response code mapping and write our own explode.

```elixir
def explode(resp) do
  resp
  |> put_message()
  |> halt()
end

defp put_mesage(resp), do: Map.get(@table, resp.status_code) |> whatever_adds_message()
```
