### ISSUE TITLE
Plenario Explorer: (Eventually) Integrate user and admin pages

### ISSUE THREAD

**Issue by HeyZoos** [UrbanCCD-UChicago/plenario2#361]
Bring them under vue, as separate routes under the vue router as opposed to distinct phoenix routes.

Story #373

**Comment by vforgione** [comment]
Wait, does this come with the implicit intention to refactor all the controllers/views to return JSON only, and make the consumer apps and admin a stand alone app?

**Comment by brlodi** [comment]
All this necessarily entails is combining the various table views and forms from the current Phoenix tree into a single page application. In practice many of those endpoints would likely be modified to return JSON.
