### ISSUE TITLE
Index Names Overflow

### ISSUE THREAD

**Issue by vforgione** [UrbanCCD-UChicago/plenario2#362]
With the new migrations that add text fields to the materialized views and indexes for those fields, we've run into a few cases where the name of the index created overflows the size allowed for names in Postgres. When this happens, similarly named fields collide and bringing up the data set fails.

For example, the data set `Chicago Transportation Department Permits` has several similarly named text fields that that with `Street`. When indexing these fields, the index name turns out to be `chicago_transportation_department_permits_view_st`. Once a second index is attempted, this explodes.

I suggest renaming indexes to `{view_name}_{field.id}`. Looking for some buy in on this idea from @HeyZoos.

**Comment by HeyZoos** [comment]
Sounds good to me, it sounds readable enough and personally I don't check the indexes very often.
