### ISSUE TITLE
API Status Codes

### ISSUE THREAD

**Issue by vforgione** [UrbanCCD-UChicago/plenario2#420]
- [x] `page_size=wrong` will 400 because it's syntactically incorrect
- [x] `page_size=0,-1` will 422 because it's semantically incorrect
- [x] `page_size=999999999` will 403 because we refuse to serve that large a page size
- [x] `page=wrong` will 400 because it's syntactically incorrect
- [x] `page=0,-1` will 422 because it's semantically incorrect
- [x] `page=99999999` will 200 and server the last useful page of data

@brlodi opened up a discussion on a PR that needed to be merged ASAP. Here is his original comment:

I'm willing to have the fight over status codes (though I agree in most cases 422 is wrong).

I believe they should be applied as follows:

Page

    page=wrong – 400 Bad Request
    page=0 – 200 OK I would generally expect an API to ignore falsy values for non-boolean parameters or take them as an explicit direction to "use defaults"; I would not make this an HTTP error at all, and simply add a note to the documentation
    page=-3 – 400 Bad Request (though it'd be great to offer reverse indexing like Python, so e.g. -1 selects the last page, in which case it would be valid)
    page=999999999999 – Probably should just return the very last (necessary incomplete) page, but if we must error then it's absolutely a 422; RFC 4918 states that 422 Unprocessable Entity is applicable when the request entity is syntactically well-formed, but semantically erroneous.

Page Size

    page_size=wrong – 400 Bad Request
    page_size=0 – 200 OK It seems straightforward enough to return the default size of page; see arguments for page=0 above
    page_size=-232 – 400 Bad Request
    page_size=1276971623108 – 403 Forbidden because we absolutely do understand the request, but we just refuse to do it because it would be a huge response

As a summary statement, I'd like to reiterate that HTTP Status Codes are intended to describe the status of the HTTP transaction itself. It is perfectly reasonable to return some amount of error status under a 200 Accepted code if the error is unrelated to the request itself, e.g. "give me the first 100 records of dataset foobar" could very well merit a response of 200 OK {"error": "Foo Bar has not had its first ingest yet, so no records are available"} (I realize that doesn't match our return spec, but the point is the request is 100% valid but there is a business behavior issue with responding)

**Comment by vforgione** [comment]
Page should be a positive, non zero integer; otherwise, it's a bad request. This goes the same for page size.

I'm not entirely convinced that 0 is a valid value, especially if we're strictly evaluating and enforcing these values.

403 seems inappropriate -- I would expect to see that for a resource I cannot access, not a query that I tried to ham fist.

422 means that we've fully interpreted the value and determined that we don't like it. The plugs only check for type and lower bound range validity and pass the request along. If a user passes page=999999999 then it's up to the database to determine if that combination of limit/offset is an error.

I've also never seen 422 used -- I know it's a legit status per the RFCs, but I have yet to see it in the wild. I think most clients are smart enough to determine that a 4xx status is an error, but are any of them actually going to handle the robust error message and adjust accordingly?

Additionally, I just hate it. I don't know why. I have this really awful, negative emotional reaction to it :)

**Comment by vforgione** [comment]
> My argument is that if we have the ability to trivially provide some more information we should do so.

You're right; and we do. That's why I put in error messages that tell the user _exactly_ what is acceptable as a value. 

Regarding page sizes and numbers: Scrivener, the library we use to paginate the database responses, substitutes default values for those parameters if they are not positive integers -- default page 1 and default page size 500. When given a page number that exceeds the last page it gives an empty list.

```
iex(3)> Repo.paginate(Meta, page: 0, page_size: 1)
%Scrivener.Page{
  entries: [
    %Plenario.Schemas.Meta{ ... }
  ],
  page_number: 1,
  page_size: 1,
  total_entries: 1,
  total_pages: 1
}

iex(4)> Repo.paginate(Meta, page: 1, page_size: 0)
%Scrivener.Page{
  entries: [
    %Plenario.Schemas.Meta{ ... }
  ],
  page_number: 1,
  page_size: 500,
  total_entries: 1,
  total_pages: 1
}

iex(5)> Repo.paginate(Meta, page: 1, page_size: -1)
%Scrivener.Page{
  entries: [
    %Plenario.Schemas.Meta{ ... }
  ],
  page_number: 1,
  page_size: 500,
  total_entries: 1,
  total_pages: 1
}

iex(6)> Repo.paginate(Meta, page: 999999999999999, page_size: 1)
%Scrivener.Page{
  entries: [],
  page_number: 999999999999999,
  page_size: 1,
  total_entries: 1,
  total_pages: 1
}
```

I don't like this behavior -- it's disingenuous to override a client's request with your own defaults and give a non-error response. If the client does not specify the parameters, then it's appropriate to use the defaults. This, to me, is a basic contract of the client/server relationship: when you request something, either you get a response that exactly satisfies your request or you get an error and are told what you did wrong.

Regarding status codes:

- 200 when your request/query succeeds, even if the result is 0 length
- 400 when you pass a bogus value
- 401 when you haven't provided credentials (N/A to the API)
- 403 when you're not allowed to access a resource (N/A to the API)
- 404 when you attempt to access an otherwise permissible resource but the specific resource 
requested doesn't exist
- 500 when we screw up

As much as I have an irrational aversion to 422, I could be persuaded that we should use it when the _app code_ determines that a parameter is bogus, and that 400 should be used when the _database_ determines the same.

**Comment by brlodi** [comment]
> Regarding page sizes and numbers: Scrivener, the library we use to paginate the database responses, substitutes default values for those parameters if they are not positive integers -- default page 1 and default page size 500. When given a page number that exceeds the last page it gives an empty list.
> I don't like this behavior -- it's disingenuous to override a client's request with your own defaults and give a non-error response. If the client does not specify the parameters, then it's appropriate to use the defaults. This, to me, is a basic contract of the client/server relationship: when you request something, either you get a response that exactly satisfies your request or you get an error and are told what you did wrong.

At risk of getting into a "stupidity of the masses" type argument, I'd again push the fact that you seem to be in a (principled, and likely not incorrect) minority here. When we're even overriding built-in behavior of a pagination library that should really raise questions of whether we're doing the socially-understood "right thing" or the Stallman/Torvalds/Thompson "right thing". I don't know that our API is the right place to make that principled stand against an apparent internet convention.

---

> 403 when you're not allowed to access a resource (N/A to the API)

That's not what 403 means:

> [RFC 2616](https://tools.ietf.org/html/rfc2616#section-10.4.4): **10.4.4 403 Forbidden**. 
The server understood the request, but is refusing to fulfill it. Authorization will not help and the request SHOULD NOT be repeated.

That's all it defines. One of the most common examples in discussions of 403, other than trying to access a file the server isn't allowed to serve, is making a request that is technically valid but would unreasonably tax the sever or its network infrastructure like requesting a huge database dump. That seems exactly applicable here.

---

> As much as I have an irrational aversion to 422, I could be persuaded that we should use it when the *app code* determines that a parameter is bogus, and that 400 should be used when the *database* determines the same.

That seems backwards to me; we should be vetting syntactic validity of parameters in the API layer and returning 400 if they fail validation. If we want to return a 422 it should be for a semantic issue, which could be caught in either the app layer or the database layer. (Technically 400 is no longer exclusively syntactic, so we could respond with that for either scenario.)

**Comment by vforgione** [comment]
By that logic then, we never throw a 403 because we're allowing for the defaults to override where clients provide awful values. And then we only 400 when the database says it can't handle the stupidity of it all.

**Comment by brlodi** [comment]
Referring back to my initial comment you copied over, the only instance I suggested a 403 was for an excessively large `page_size`.

**Comment by vforgione** [comment]
But then why not let the default value handle it? If we validate an arbitrary upper bound then we should also validate a lower bound. If on one end we allow trash values and then supplement a sane default, why would we not on the other?

**Comment by vforgione** [comment]
Tagging this as an action item for #426

**Comment by vforgione** [comment]
Here is my compromise:

```
page=wrong        400 - page must be a positive integer
page=0            422 - page must be a positive integer
page=-3           422 - page must be a positive integer
page=9999999      200 and let db return an empty page

page_size=wrong   400 - page size must be a positive integer not exceeding N
page_size=0       422 - page size must be a positive integer not exceeding N
page_size=-3      422 - page size must be a positive integer not exceeding N
page_size=999999  403 - page size must be a positive integer not exceeding N
```

**Comment by brlodi** [comment]
Unless I'm misunderstanding, I think it actually already has the behavior I'm looking for: drewolson/scrivener_ecto#43

**Comment by vforgione** [comment]
See my earlier example of

```
iex(6)> Repo.paginate(Meta, page: 999999999999999, page_size: 1)
%Scrivener.Page{
  entries: [],
  page_number: 999999999999999,
  page_size: 1,
  total_entries: 1,
  total_pages: 1
}
```

**Comment by brlodi** [comment]
It works if you pass `page_number` instead of just `page`:

```elixir
iex(5)> Repo.paginate(Meta, page_number: 999999999999999, page_size: 1)
%Scrivener.Page{
  entries: [
    %Plenario.Schemas.Meta{ ⋯ }
  ],
  page_number: 1,
  page_size: 1,
  total_entries: 1,
  total_pages: 1
}
```

**Comment by vforgione** [comment]
Never mind; apparently I can't read my own output. Scrivener sends a count request anyway, so whatever. It's a really bad idea, but there it is. I'll be switching all our pagination calls to use `page_number` instead of `page`.

Final result:

- [ ] `page_size=wrong` will 400 because it's syntactically incorrect
- [ ] `page_size=0,-1` will 422 because it's semantically incorrect
- [ ] `page_size=999999999` will 403 because we refuse to serve that large a page size
- [ ] `page=wrong` will 400 because it's syntactically incorrect
- [ ] `page=0,-1` will 422 because it's semantically incorrect
- [ ] `page=99999999` will 200 and server the last useful page of data
