### ISSUE TITLE
Remove Error GIFs

### ISSUE THREAD

**Issue by vforgione** [UrbanCCD-UChicago/plenario2#430]
Right now we have some GIFs for our error pages. It was a fun little treat while we were developing the app, but now it's just unprofessional crap as we start planning a production release.

That, and they're massive in size.

**Comment by brlodi** [comment]
I can take on designing a nice-looking error page template. On a scale from NGINX error to "Meet the Dogs of Amazon" how serious do we want it to be? Some levity on error pages is a positive thing in my mind.

**Comment by vforgione** [comment]
I think our 404 GIF is alright, but it _so freaking heavy_. Maybe something like that. I agree, a little levity if 404s is good; same with 500.

403/1 on the other hand should be a stark _No Access_ kind of message.

**Comment by brlodi** [comment]
I'm pretty sure the 404 GIF is a screen capture of a CSS-animations-powered 404 page somewhere, so it would be pretty doable to have something equally nice with a much smaller footprint.
