### ISSUE TITLE
Maps not rendering in search results

### ISSUE THREAD

**Issue by vforgione** [UrbanCCD-UChicago/plenario2#441]
The first data set map renders, but then the rest fail to render.

## Are there any specific error messages?
SyntaxError: redeclaration of let pt_193

I would assume this is because of the scripts in the template. Maybe it's fixed with the front end stuff you guys are pushing, or maybe we need to change point declarations back to `var`.

**Comment by brlodi** [comment]
It will be fixed with the Vue explorer. All of that logic is gone.
