### ISSUE TITLE
Search result map getting mangled

### ISSUE THREAD

**Issue by vforgione** [UrbanCCD-UChicago/plenario2#442]
Vinny no like. :cry: 

![screenshot_2018-08-21 plenario](https://user-images.githubusercontent.com/4360430/44422021-b3a50e80-a547-11e8-9656-2282ebe33a5b.png)

**Comment by brlodi** [comment]
I'm unable to reproduce this in any browser under macOS. Did you do anything in particular to trigger it, like resizing the window?

**Comment by vforgione** [comment]
Nope. Ubuntu 18, Firefox 61.

**Comment by brlodi** [comment]
I can confirm the query string is fine, it's a valid set of coords like below. We're just choking on it for some reason.

`[[41.915770455502454,-87.97443773176727],[42.05863606922915,-87.97443773176727],[42.05863606922915,-87.58449768179747],[41.915770455502454,-87.58449768179747]]`

**Comment by brlodi** [comment]
This is possibly a cascading result of the issue in #441, since that's breaking continuing JavaScript execution on the page.
