### ISSUE TITLE
RFC: Entity API Design

### ISSUE THREAD

**Issue by vforgione** [UrbanCCD-UChicago/plenario2#71]
As we begin to plan the API portion of the application, I feel like it's
important to get as much feedback from as many people as possible so that
we have an exceptionally well tuned API.

*Caveat:* the one thing that is not up for debate is the response type. We will
be using JSON. YAML is not a good option for APIs and XML has waned too
significantly in usage that it's not worth supporting. JSON is, for better or
worse, the _lingua franca_ of the web.

*Caveat to the caveat:* We're also going to encode everything using UTF-8. In
the future this might be bumped to UTF-16 to be more inclusive, but for right
now I don't see much traction for that in the wider software world.

With those caveats in place, we have a decent scope to start off with. I think
most of us have some pretty common and basic expectations:

- all fields are properly typed (numbers are not stings!)
- IDs are present in all objects

What remains to be decided is how we want to handle more nuanced subjects -- is
there a need to include URIs in the objects, how do we want to handle nested
objects, how do we want to handle creating and updating related objects?

For example, we have `data sets` and those data sets are owned by a `user` and
the data sets have `fields`. If we request a single data set, do we want to
embed the user and its fields (1), or should they be their ID fields (2), or 
should they be URIs to the entities (3)?

```
(1)
{
  "id": 12345,
  "name": "Tree Trimming Requests",
  "source_url": "https://data.cityofchicago.org/tree-trimming",
  "source_type": "csv",
  "owner": {
    "id": 2345,
    "name": "Tom",
    "email": "tom@example.com"
  },
  "data_set_fields": [
    {
      "id": 4321,
      "name": "call_id",
      "type": "text"
    },
    {
      "id": 4322,
      "name": "location",
      "type": "text"
    }
  ]
}
```

```
(2)
{
  "id": 12345,
  "name": "Tree Trimming Requests",
  "source_url": "https://data.cityofchicago.org/tree-trimming",
  "source_type": "csv",
  "owner": 2345,
  "data_set_fields": [
    4321,
    4322
  ]
}
```

```
(3)
{
  "id": 12345,
  "name": "Tree Trimming Requests",
  "source_url": "https://data.cityofchicago.org/tree-trimming",
  "source_type": "csv",
  "owner": "/users/2345",
  "data_set_fields": [
    "/data-set-fields/4321",
    "/data-set-fields/4322"
  ]
}
```

It also follows that some entities don't really have any meaning on their own,
that they need some additional context -- `data_set_fields` for example. So, as
we design this, does it make sense to provide their context in some way?

This might be a routing issue -- my ideas for this involve giving context to
the field (or whatever else) through their URI:

```
GET /data-sets/:data_set_id/fields/:field_id

{
  "data_set_id": "whatever",
  "field": "data",
  ...
}
```

**Comment by levyj** [comment]
My preferences from highest to lowest would be 1, 3, 2.

Of course, if the size and/or frequency of the requests/responses get large, the efficiency of a smaller JSON response could win out. That may be the point in the first place.

**Comment by vforgione** [comment]
There's another option: [JSON API](http://jsonapi.org/). I've thought about using it in the past, but I've never pulled the trigger. Maybe it makes sense to think about implementing it here since there could be a lot of redundant objects.

**Comment by vforgione** [comment]
Docs for the API are at https://github.com/UrbanCCD-UChicago/plenario2/wiki/API-Documentation .
