### ISSUE TITLE
Spruce up the detail page

### ISSUE THREAD

**Issue by HeyZoos** [UrbanCCD-UChicago/plenario2#85]

**Comment by vforgione** [comment]
i'm trying to find an old screenshot of the way you had it before... any chance you might have one?

**Comment by HeyZoos** [comment]
![selection_001](https://user-images.githubusercontent.com/9408481/34011546-65977bfc-e0de-11e7-99f6-c1eeb77709fb.png)

**Comment by vforgione** [comment]
closed with #153
