### ISSUE TITLE
`meta` vs `meta_id`

### ISSUE THREAD

**Issue by vforgione** [UrbanCCD-UChicago/plenario2#92]
As I've been documenting the libs, I keep seeing switches in parameters. Here's 3 ideas on how to fix it:

1. we standardize on `meta_id` or `${whatever schema name}_id` as the param
1. we standardize on passing the instance
1. we keep both, have 2 functions with guard clauses

I like the last one -- it gives us the maximum flexibility. For example:

```elixir
def list_for_meta(meta) when not is_integer(meta) do
  list_for_meta(meta.id)
end

def list_for_meta(meta_id) when is_integer(meta_id) do
  ...
end
```

Thoughts from @HeyZoos and @sanilio?

**Comment by HeyZoos** [comment]
I like the idea of keeping both, we could also standardize on our naming conventions. ${schema} could always refer to a struct, and to refer to any target properties you have to use #{schema}_${prop}

**Comment by sanilio** [comment]
I agree keeping both and having the schema prefix sounds good

**Comment by vforgione** [comment]
this also goes for the `get_from_id` vs `get_by_id`... i'm rolling with the `by`.
